; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/Users/clinton/Projects/codemash/todo-httpkit/src/clj/todo/todo.clj

(ns todo.todo)

(println "hi")
